### PR TITLE
V2

### PR DESCRIPTION
**Pull request by fdcastel**
Major code revamp. Please review and comment. 

Most tests passing (running against firebird 2.5, 3.0 and 4.0). Around ~40~50 failing.

- New "firebird" dialect (based on firebird-driver, Firebird 3.0+ only)
- Code in sync with SqlAlchemy v2.0 PostgreSQL Implementation (with some missing parts, still)
- Scripts (Windows x64 only) to download Firebird 2.5, 3.0 and 4.0 and setup a test environment using Firebird Embedded

### CODE REVIEW

**Comment by fdcastel** [comment]
Rebased with latest `main`.

**Comment by fdcastel** [comment]
My fault. I renamed the scripts as a last-minute change. Fixed.

`t.ps1` is now `run.test.ps1`

**Comment by pauldex** [comment]
Get "TypeError: connect() got an unexpected keyword argument 'fb_library_name'" with all version of firebird and drivers.  SQLA version 2.0.12

**Comment by pauldex** [comment]
Got it - uri changed in SQLA 2

**Comment by fdcastel** [comment]
@pauldex how is going? May I help you with anything?

I see you have been doing some changes in `main` branch which appears to be from this PR. But this will cause havok to rebase later. 😟

**Comment by fdcastel** [comment]
BTW: I forgot I had made some changes into my SQLAlchemy code for some tests to pass. 

I did it in belief SQLAlchemy tests were wrong in this case (spoilers: they weren't).

Today I discussed them with SQLAlchemy authors.

- One was caused by a non-compliant return in `firebird-driver`. I submitted a PR [here](https://github.com/FirebirdSQL/python3-driver/issues/20).

- The other was [this test](https://github.com/pauldex/sqlalchemy-firebird/pull/48/commits/1f973ce6cf1774146ae67f720dfdf36a556fe89e) which turned out impossible to be made Firebird-compatible and it was disabled.

With theses changes Firebird 4.0 with `firebird-driver` is failing on **35** tests now.

I intend to implement `get_multi_*` methods in a few days, which will reduce this number yet more.

**Comment by pauldex** [comment]
It’s going well.  Thanks for all the work you’ve been doing.

 

I’ve been experimenting with a partial merge from your pr because the changes in provision.py don’t work with SQLAlchemy 1.4 (fails on ‘from sqlalchemy import Engine’).  

 

We can do the merge as so as the tests can be run using SQLAlchemy version 1.4 in addition to version 2.  Don’t worry about the rebase, I can revert to a compatible main before merging.

 

Paul

**Comment by fdcastel** [comment]
Understood. Great!

You are right. I completely forgot about 1.4.

I will hold my next changes and focus on 1.4 compatibility, then, in the
next days.

**Comment by pauldex** [comment]
Thanks – I’m looking forward to seeing the updates!

 

Paul

**Comment by fdcastel** [comment]
Really really _almost_ there.

# SQLAlchemy 2.0:
  - Firebird 5.0: **All tests passing!** 
  - Firebird 4.0: 1 test failing due to unsupported multiple rows in `UPDATE ... RETURNING`.
  - Firebird 3.0: 1 test failing due to unsupported multiple rows in `UPDATE ... RETURNING`.
  - Firebird 2.5: 2 tests failing due unsupported IDENTITY columns and multiple rows in `UPDATE ... RETURNING`.

# SQLAlchemy 1.4:
  - Firebird 5.0: **All tests passing!**
  - Firebird 4.0: **All tests passing!** 
  - Firebird 3.0: 5 tests failing due unsupported IDENTITY columns.
  - Firebird 2.5: 19 tests failing due unsupported IDENTITY columns and `CREATE SEQUENCE ... START WITH`.

## Notes

Two tests were adapted because SQLAlchemy implementation caused problem in Firebird:
  - `test_get_unique_constraints`
  - `test_reflect_expression_based_indexes`

Several other tests were disabled in some specific Firebird versions. Please see `test_suite.py`.

However, in a few cases (the remaining failing tests) I didn't find a way to disable them for specific Firebird versions. That's why we cannot, yet, get a clean run from the entire test suite.

After that there is also some remaining problems:
- Better documentation / Development notes
- Tests hanging (why???)
- TODOs commented in code

I'm going to take a few days off. Please review everything and send me your considerations.

**Comment by fdcastel** [comment]
P.S.: May I suggest we release this version as `2.0.0`?

**Comment by fdcastel** [comment]
Also. To remove `requirements.txt` / `requirements_dev.txt` and use the newer `pyproject.toml` style for dependencies.

**Comment by fdcastel** [comment]
@pauldex May I help you with anything else needed to release a 2.0 version?

**Comment by pauldex** [comment]
I’m having some difficulty in getting the new 2.0 version to work without having fdb installed.

**Comment by fdcastel** [comment]
Hm. Where? Could you point me where it is happening?

What is the error message you are getting?
