### ISSUE TITLE
SQLAlchemy 2.0 support status?

### ISSUE THREAD

**Issue by fdcastel** [pauldex/sqlalchemy-firebird#43]
[SQLAlchemy 2.0 was officially released in january](https://www.sqlalchemy.org/blog/2023/01/26/sqlalchemy-2.0.0-released/)

> With this release, the default version of SQLAlchemy that will install when one runs pip install sqlalchemy will be version 2.0.

I'm looking to migrate some production projects from SQLAlchemy 1.4 to 2.0. 

But I'm wondering **will this project in its current state support it?**

I'm asking because I didn't see any commits related to 2.0 compatibility. And there are significant changes in SQLAlchemy 2.0.

**Comment by fdcastel** [comment]
When using

```
firebird-driver = "1.8.0"
sqlalchemy = "2.0.8"
sqlalchemy-firebird = "0.7.6"
```

`create_engine()` gives the following warning:

```
 SADeprecationWarning: The dbapi() classmethod on dialect classes has been renamed to import_dbapi().  Implement an 
import_dbapi() classmethod directly on class <class 'sqlalchemy_firebird.fdb.FBDialect_fdb'> to remove this warning; the old .dbapi() classmethod may be maintained for backwards compatibility.
```

**Comment by fdcastel** [comment]
Tests are also failing. `pytest` seems to fail very soon, in tests discovery phase:

```
(venv) PS C:\Temp\sqlalchemy-firebird> pytest    
==================================================================================================== sqlalchemy installation ====================================================================================================
SQLAlchemy 2.0.8 (user site loaded)
Path: C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\sqlalchemy\__init__.py
compiled extension enabled, e.g. C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\sqlalchemy\cyextension\util.cp310-win_amd64.pyd
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\_pytest\main.py", line 268, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\sqlalchemy\testing\plugin\pytestplugin.py", line 163, in pytest_sessionstart
INTERNALERROR>     asyncio._assume_async(plugin_base.post_begin)
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\sqlalchemy\testing\asyncio.py", line 53, in _assume_async
INTERNALERROR>     return _util_async_run(fn, *args, **kwargs)
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 218, in _util_async_run
INTERNALERROR>     return loop.run_until_complete(greenlet_spawn(fn, *args, **kwargs))
INTERNALERROR>   File "C:\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
INTERNALERROR>     return future.result()
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 154, in greenlet_spawn
INTERNALERROR>     result = context.switch(*args, **kwargs)
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\sqlalchemy\testing\plugin\plugin_base.py", line 294, in post_begin
INTERNALERROR>     fn(options, file_config)
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\sqlalchemy\testing\plugin\plugin_base.py", line 460, in _engine_uri
INTERNALERROR>     cfg = provision.setup_config(
INTERNALERROR>   File "C:\Temp\sqlalchemy-firebird\venv\lib\site-packages\sqlalchemy\testing\provision.py", line 70, in setup_config
INTERNALERROR>     dialect = sa_url.make_url(db_url).get_dialect()
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'get_dialect'
```

I updated the  `[db]` section on my `setup.cfg` to a valid Firebird database on my machine.

**Comment by fdcastel** [comment]
I'm working on a SQLAlchemy 2.0 port [here](https://github.com/fdcastel/sqlalchemy-firebird/tree/sqlalchemy2)

I'll submit a PR when appropriate.

**Comment by pauldex** [comment]
Thanks.  I haven't been able to get pytest to work at all with SQLAlchemy 2.  It can't find the database from the [db] section in setup.cfg, although switching back to an earlier SQLA version has no problems at all.  How did you get it to read?

**Comment by fdcastel** [comment]
Strange. I didn't get this problem. 

I'm abroad until Apr, 19. I'll return to this ASAP.
